### ISSUE TITLE
babel es2015 is installed as a devDependency

### ISSUE THREAD

**Issue by LookRain** [surmon-china/vue-awesome-swiper#108]
Basically if you start a fresh vue-cli project and pull in vue-awesome-swiper, nothing works.

The following error is given after running `npm run dev`:
```
Module build failed: Error: Couldn't find preset "es2015" relative to directory "C:\\Users\\Rain\\Documents\\swiper-with-vuetify\\node_modules\\vue-awesome-swiper"
```

#### Steps to reproduce
```
vue init webpack app
npm install
// install vue-awesome-swiper and import in main javascript file
npm run dev
```
#### What is Expected?		
Swiper should work without a problem,

#### What is actually happening?
Console outputs errors:
```
Module build failed: Error: Couldn't find preset "es2015" relative to directory "C:\\Users\\Rain\\Documents\\swiper-with-vuetify\\node_modules\\vue-awesome-swiper"
    at C:\Users\Rain\Documents\swiper-with-vuetify\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (C:\Users\Rain\Documents\swiper-with-vuetify\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (C:\Users\Rain\Documents\swiper-with-vuetify\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (C:\Users\Rain\Documents\swiper-with-vuetify\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (C:\Users\Rain\Documents\swiper-with-vuetify\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\Users\Rain\Documents\swiper-with-vuetify\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\Users\Rain\Documents\swiper-with-vuetify\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\Users\Rain\Documents\swiper-with-vuetify\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\Users\Rain\Documents\swiper-with-vuetify\node_modules\babel-loader\lib\index.js:46:20)
    at Object.module.exports (C:\Users\Rain\Documents\swiper-with-vuetify\node_modules\babel-loader\lib\index.js:163:20)

 @ ./~/vue-awesome-swiper/swiper.vue 4:2-87
 @ ./~/vue-awesome-swiper/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js
```

**Comment by surmon-china** [comment]
I will test.

**Comment by surmon-china** [comment]
Update to v2.5.0 please, it will be work!
