### ISSUE TITLE
Doesn't work with NPM and webpack

### ISSUE THREAD

**Issue by aaronjpitts** [surmon-china/vue-awesome-swiper#41]
Hi,

When using your plugin via NPM and webpack, when I build the project it gives the below error:

```
ERROR in ./~/swiper/dist/css/swiper.css
Module parse failed: /Users/aaronpitts/Sites/new/node_modules/swiper/dist/css/swiper.css Unexpected token (15:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (15:0)
    at Parser.pp$4.raise (/Users/aaronpitts/Sites/new/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/aaronpitts/Sites/new/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/Users/aaronpitts/Sites/new/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/Users/aaronpitts/Sites/new/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/Users/aaronpitts/Sites/new/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/Users/aaronpitts/Sites/new/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/Users/aaronpitts/Sites/new/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/Users/aaronpitts/Sites/new/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/Users/aaronpitts/Sites/new/node_modules/acorn/dist/acorn.js:1573:21)
    at Parser.pp$1.parseStatement (/Users/aaronpitts/Sites/new/node_modules/acorn/dist/acorn.js:727:47)
    at Parser.pp$1.parseTopLevel (/Users/aaronpitts/Sites/new/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Users/aaronpitts/Sites/new/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Users/aaronpitts/Sites/new/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/Users/aaronpitts/Sites/new/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/aaronpitts/Sites/new/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/aaronpitts/Sites/new/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/aaronpitts/Sites/new/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/aaronpitts/Sites/new/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/aaronpitts/Sites/new/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/aaronpitts/Sites/new/node_modules/graceful-fs/graceful-fs.js:76:16
    at fs.js:334:14
    at /Users/aaronpitts/Sites/new/node_modules/graceful-fs/graceful-fs.js:42:10
    at FSReqWrap.oncomplete (fs.js:95:15)
 @ ./~/babel-loader?presets[]=es2015&plugins[]=transform-runtime&comments=false!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vue-awesome-swiper/swiper.vue 10:2-39
```

Any ideas? 
Man thanks

**Comment by surmon-china** [comment]
```bash
npm install css-loader style-loader --save
```

**Comment by aaronjpitts** [comment]
I have those packages installed and the latest versions. I still get the below:

`ERROR in /Users/aaronpitts/Sites/new/node_modules/css-loader/node_modules/loader-utils/lib/index.js:3
const getOptions = require("./getOptions");
^^^^^
Use of const in strict mode.
 @ ./~/vue-style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js!./~/less-loader!./~/vue-loader/lib/selector.js?type=style&index=0!./~/vue-google-maps/src/components/map.vue 4:14-210

ERROR in /Users/aaronpitts/Sites/new/node_modules/css-loader/node_modules/loader-utils/lib/index.js:3
const getOptions = require("./getOptions");
^^^^^
Use of const in strict mode.
 @ ./~/vue-style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js!./~/vue-loader/lib/selector.js?type=style&index=0!./~/vue-spinner/src/PulseLoader.vue 4:14-177

ERROR in ./~/swiper/dist/css/swiper.css
Module parse failed: /Users/aaronpitts/Sites/new/node_modules/swiper/dist/css/swiper.css Unexpected token (15:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (15:0)
    at Parser.pp$4.raise (/Users/aaronpitts/Sites/new/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/aaronpitts/Sites/new/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/Users/aaronpitts/Sites/new/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/Users/aaronpitts/Sites/new/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/Users/aaronpitts/Sites/new/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/Users/aaronpitts/Sites/new/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/Users/aaronpitts/Sites/new/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/Users/aaronpitts/Sites/new/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/Users/aaronpitts/Sites/new/node_modules/acorn/dist/acorn.js:1573:21)
    at Parser.pp$1.parseStatement (/Users/aaronpitts/Sites/new/node_modules/acorn/dist/acorn.js:727:47)
    at Parser.pp$1.parseTopLevel (/Users/aaronpitts/Sites/new/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Users/aaronpitts/Sites/new/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Users/aaronpitts/Sites/new/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/Users/aaronpitts/Sites/new/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/aaronpitts/Sites/new/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/aaronpitts/Sites/new/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/aaronpitts/Sites/new/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/aaronpitts/Sites/new/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/aaronpitts/Sites/new/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/aaronpitts/Sites/new/node_modules/graceful-fs/graceful-fs.js:76:16
    at fs.js:334:14
    at /Users/aaronpitts/Sites/new/node_modules/graceful-fs/graceful-fs.js:42:10
    at FSReqWrap.oncomplete (fs.js:95:15)
 @ ./~/babel-loader?presets[]=es2015&plugins[]=transform-runtime&comments=false!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vue-awesome-swiper/swiper.vue 10:2-39`

**Comment by aslak01** [comment]
You need to set up your webpack.conf to use the loaders. Pasting this block in the loader section of my webpack.conf works for me:

```
      {
        test: /\.(css|scss)$/,
        loader: 'style-loader!css-loader'
      },
```
You'll need to restart your dev server before it will work. I'm just setting this up on a fresh vue-cli webpack-simple template, and came here to be reminded what to do. Would be nice if it was referenced in the readme.

**Comment by robertjchristian** [comment]
Could be conflicts in node_modules folder.  Good idea to make sure it's clean.

Try:

`rm -rf node_modules && npm install`
