### ISSUE TITLE
Gridsome Support, the build does not work

### ISSUE THREAD

**Issue by jsappme** [surmon-china/vue-awesome-swiper#586]
I am trying to use this module on my Gridsome Vue app. It works fine in development but when I try to build it, it gives me the following error log:

```
Could not generate HTML for "/":
ReferenceError: window is not defined
    at Object.<anonymous> (node_modules/vue-awesome-swiper/dist/vue-awesome-swiper.js:1:3156)
    at t (node_modules/vue-awesome-swiper/dist/vue-awesome-swiper.js:1:429)
    at Object.<anonymous> (node_modules/vue-awesome-swiper/dist/vue-awesome-swiper.js:1:1887)
    at t (node_modules/vue-awesome-swiper/dist/vue-awesome-swiper.js:1:429)
    at Object.<anonymous> (node_modules/vue-awesome-swiper/dist/vue-awesome-swiper.js:1:2151)
    at t (node_modules/vue-awesome-swiper/dist/vue-awesome-swiper.js:1:429)
    at assets/js/vendors~page--src--pages--index-vue.41f998fb.js:7:583
    at assets/js/vendors~page--src--pages--index-vue.41f998fb.js:7:592
    at exports.modules.292 (node_modules/vue-awesome-swiper/dist/vue-awesome-swiper.js:1:64)
    at Object.292 (node_modules/vue-awesome-swiper/dist/vue-awesome-swiper.js:1:317)
error Command failed with exit code 1.
```

I tried a few solutions but without success.

I also tried this https://gridsome.org/docs/assets-scripts/#without-ssr-support it does not give any error anymore but the swiper does not work, it acts like a simple <div>

**Comment by vdilly** [comment]
Got it working with gridsome build like this :
```html
<ClientOnly>
  <div v-swiper:mySwiper="swiperOption" class="hp-slider">
    <div class="swiper-wrapper">
      <div class="swiper-slide" v-for="i in 6" :key="i">
        <div class="swiper-slide__inner">Slide {{i}}</div>
      </div>
    </div>
  </div>
</ClientOnly>
```
```js
import Vue from "vue";

export default {
  data() {
    return {
      swiperOption: {...}
    },
  mounted() {
    if (process.browser) {
      const VueAwesomeSwiper = require("vue-awesome-swiper/dist/ssr");
      Vue.use(VueAwesomeSwiper);
    }
  },
}
```

**Comment by jasontheiler** [comment]
@vdilly While this solution works, it really defeats the purpose of SSR. You could as well just go ahead and use the default `"vue-awesome-swiper"` import, since you only render it on the client side anyway.

I have the same issue with Gridsome and this module, like @jsappme does. I would still like to know if there is a true SSR solution for this problem.

**Comment by surmon-china** [comment]
[v4.0.0](https://github.com/surmon-china/vue-awesome-swiper/tree/v4.0.0-rc.0) released!

@jsappme @vdilly 
You can see the latest usage of directive [here](https://github.com/surmon-china/surmon-china.github.io/tree/source/projects/vue-awesome-swiper/nuxt).

And try:

```html
<div v-swiper:mySwiper="swiperOption" class="hp-slider">
  <div class="swiper-wrapper">
    <div class="swiper-slide" v-for="i in 6" :key="i">
      <div class="swiper-slide__inner">Slide {{i}}</div>
    </div>
  </div>
</div>
```

```js
import Vue from 'vue';

export default {
  directives: !process.browser ? {} : {
    swiper: require('vue-awesome-swiper').directive
  },
  data() {
    return {
      swiperOption: {...}
    }
  },
  mounted() {
    console.log('Swiper instance:', this.mySwiper)
  }
}
```

:)
